'\" t
.\"     Title: dnstable_lookup
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 01/30/2023
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DNSTABLE_LOOKUP" "1" "01/30/2023" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dnstable_lookup \- lookup individual records in a dnstable data file or set of data files
.SH "SYNOPSIS"
.sp
\fBdnstable_lookup\fR [\fB\-cjJRu\fR] [\fB\-aAbB datetime\fR] [\fB\-O #\fR] \fBrrset\fR <OWNER> [<RRTYPE> [<BAILIWICK>]]
.sp
\fBdnstable_lookup\fR [\fB\-cjJRu\fR] [\fB\-aAbB datetime\fR] [\fB\-O #\fR] \fBrdata ip\fR <ADDRESS | RANGE | PREFIX>
.sp
\fBdnstable_lookup\fR [\fB\-cjJRu\fR] [\fB\-aAbB datetime\fR] [\fB\-O #\fR] \fBrdata raw\fR <HEX STRING> [<RRTYPE>]
.sp
\fBdnstable_lookup\fR [\fB\-cjJRu\fR] [\fB\-aAbB datetime\fR] [\fB\-O #\fR] \fBrdata name\fR <RDATA NAME> [<RRTYPE>]
.sp
\fBdnstable_lookup\fR [\fB\-jJu\fR] [\fB\-O #\fR] \fBtime_range\fR
.sp
\fBdnstable_lookup\fR [\fB\-jJu\fR] [\fB\-O #\fR] \fBversion\fR [<ETYPE>]
.SH "DESCRIPTION"
.sp
Looks up records in a dnstable data file or fileset\&. Results are printed to stdout in an ad\-hoc text format or in JSON format if \fB\-j\fR or \fB\-J\fR are given\&. The matching may be done based on the date and time the DNS record was first and/or last observed\&.
.sp
\fBdnstable_lookup rrset\fR returns RRsets matching the specified owner name (wildcards permitted)\&. A resource record type and bailiwick domain name can optionally be specified\&.
.sp
\fBdnstable_lookup rdata ip\fR returns A or AAAA type Resource Records matching the specified IP address, IP prefix, or IP range\&.
.sp
\fBdnstable_lookup rdata raw\fR returns Resource Records whose record data matches the specified data value, expressed as a hexadecimal string\&.
.sp
\fBdnstable_lookup rdata name\fR returns Resource Records whose record data matches the specified domain name\&.
.sp
\fBdnstable_lookup time_range\fR returns an entry containing the time range for data within the data file or fileset\&.
.sp
\fBdnstable_lookup version\fR returns version entries\&. The optional \fBETYPE\fR parameter can be used to request a specific type\(cqs version\&. \fBETYPE\fR may be one of \fBrrset\fR, \fBrrset_name\fR, \fBrdata\fR, or \fBrdata_name\fR
.SH "OPTIONS"
.PP
\fB\-a\fR \fIdatetime\fR
.RS 4
Select results with recorded first seen after this
\fIdatetime\fR\&. See the DATE TIME SPECIFICATION section below for details\&.
.RE
.PP
\fB\-A\fR \fIdatetime\fR
.RS 4
Select results with recorded last seen after this
\fIdatetime\fR\&. See the DATE TIME SPECIFICATION section below for details\&.
.RE
.PP
\fB\-b\fR \fIdatetime\fR
.RS 4
Select results with recorded last seen before this
\fIdatetime\fR\&. See the DATE TIME SPECIFICATION section below for details\&.
.RE
.PP
\fB\-B\fR \fIdatetime\fR
.RS 4
Select results with recorded first seen before this
\fIdatetime\fR\&. See the DATE TIME SPECIFICATION section below for details\&.
.RE
.PP
\fB\-c\fR
.RS 4
This enables complete (strict) matching semantics so no entries with a first or last observed time outside the provided time range will be matched\&. By default, time\-based filtering with
\fB\-A\fR
and
\fB\-B\fR
will select results if any of the time is within the range (even if some are outside the range)\&. The
\fB\-c\fR
means it will not output the entry if it was also seen outside the time range\&.
.RE
.PP
\fB\-j\fR
.RS 4
Use JSON format for output, with timestamps in epoch time (seconds since epoch)\&. Default is
\fIdig\fR
presentation format\&. One JSON\-formatted entry per line will be printed\&.
.RE
.PP
\fB\-J\fR
.RS 4
Use JSON format for output, with timestamps in human time (RFC3339 format)\&. Default is
\fIdig\fR
presentation format\&. One JSON\-formatted entry per line will be printed\&.
.RE
.PP
\fB\-n\fR
.RS 4
Output the number of matching entries found, rather than details about each entry\&.
.RE
.PP
\fB\-R\fR, \fB\-\-raw\fR
.RS 4
When using a JSON format for output, add a hex representation of the raw rdata and the rrtype\&.
.RE
.PP
\fB\-u\fR
.RS 4
Output unaggregated results; default is aggregated results\&. This is only valid with a setfile\&.
.RE
.PP
\fB\-O #\fR
.RS 4
Offset (e\&.g\&. skip) the first # results\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
Exactly one of the following environment variables must be set in order to specify the dnstable data file(s) to query\&.
.PP
\fBDNSTABLE_FNAME\fR
.RS 4
Path to a single dnstable data file\&.
.RE
.PP
\fBDNSTABLE_SETFILE\fR
.RS 4
Path to a "set file", a text file containing a newline separated list of dnstable data files on the filesystem\&. Results from all of the data files will be merged\&.
.RE
.SH "DATE TIME SPECIFICATION"
.sp
The \fB\-a\fR, \fB\-A\fR, \fB\-b\fR, and \fB\-B\fR options support various date or time formats\&.
.sp
The date may be represented using \fBstrptime(3)\fR ISO 8601 date formats: %Y\-%m\-%d, %Y\-%m\-%d %H:%M:%S (space separated), %Y\-%m\-%dT%H:%M:%S ("T" separated), and %Y\-%m\-%dT%H:%M:%SZ ("T" separated with trailing "Z" for Zulu timezone)\&.
.sp
The date may be represented using absolute Unix epoch time in seconds, e\&.g\&., 1577880000 for January 1, 2020 noon\&.
.sp
The date may be represented using negative relative numeric time in seconds such as "\-300" is 5 minutes ago\&.
.sp
The date may be represented using timing mnemonics relative to current time: W for weeks, D for days, H for hours, M for minutes, and S for seconds\&. For example, "52w3d" would be one year and three days before the current date (to the second); and "4H30M" is four and a half hours before the current time\&. (The letters are case insensitive\&.)
.sp
Due to the parser design, it won\(cqt accept a value of zero or "1970\-01\-01T00:00:00Z" or earlier\&.
.SH "EXAMPLES"
.sp
$ export DNSTABLE_FNAME=/path/to/dns\&.mtbl
.sp
$ dnstable_lookup rrset www\&.example\&.com
.sp
$ dnstable_lookup rrset example\&.com ns com
.sp
$ dnstable_lookup rdata ip 192\&.0\&.2\&.1
.sp
$ dnstable_lookup rdata ip 198\&.51\&.100\&.0/24
.sp
$ dnstable_lookup rdata ip 203\&.0\&.113\&.1\-203\&.0\&.113\&.100
.sp
$ dnstable_lookup \-j rdata ip 2001:db8::/32
.sp
$ dnstable_lookup \-R \-j rdata ip 2001:db8::/32
.sp
$ dnstable_lookup \-u rdata ip 2001:db8::/32
.sp
$ dnstable_lookup \-O 10 rdata ip 2001:db8::/32
.sp
$ dnstable_lookup rdata raw c00505f1
.sp
$ dnstable_lookup rdata name BLACKHOLE\-1\&.IANA\&.ORG
.sp
$ dnstable_lookup \-B "2022\-11\-09 22:59:59" rrset example\&.com
