'\" t
.\"     Title: dnstable_query
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/06/2021
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DNSTABLE_QUERY" "3" "04/06/2021" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dnstable_query \- dnstable query objects
.SH "SYNOPSIS"
.sp
\fB#include <dnstable\&.h>\fR
.sp
.nf
\fBtypedef enum {
    \fR\fB\fIDNSTABLE_QUERY_TYPE_RRSET\fR\fR\fB,
    \fR\fB\fIDNSTABLE_QUERY_TYPE_RDATA_NAME\fR\fR\fB,
    \fR\fB\fIDNSTABLE_QUERY_TYPE_RDATA_IP\fR\fR\fB,
    \fR\fB\fIDNSTABLE_QUERY_TYPE_RDATA_RAW\fR\fR\fB,
    \fR\fB\fIDNSTABLE_QUERY_TYPE_TIME_RANGE\fR\fR\fB,
    \fR\fB\fIDNSTABLE_QUERY_TYPE_VERSION\fR\fR\fB,
} dnstable_query_type;\fR
.fi
.sp
.nf
\fBstruct dnstable_query *
dnstable_query_init(dnstable_query_type);\fR
.fi
.sp
.nf
\fBvoid
dnstable_query_destroy(struct dnstable_query **\fR\fB\fIq\fR\fR\fB);\fR
.fi
.sp
.nf
\fBconst char *
dnstable_query_get_error(struct dnstable_query *\fR\fB\fIq\fR\fR\fB);\fR
.fi
.sp
.nf
\fBdnstable_res
dnstable_query_set_data(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    const char *\fR\fB\fIdata\fR\fR\fB);\fR
.fi
.sp
.nf
\fBdnstable_res
dnstable_query_set_rrtype(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    const char *\fR\fB\fIrrtype\fR\fR\fB);\fR
.fi
.sp
.nf
\fBdnstable_res
dnstable_query_set_offset(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    uint64_t \fR\fB\fIoffset\fR\fR\fB);\fR
.fi
.sp
.nf
\fBdnstable_res
dnstable_query_set_aggregated(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    bool \fR\fB\fIaggregated\fR\fR\fB);\fR
.fi
.sp
.nf
\fBvoid
dnstable_query_set_case_sensitive(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    bool \fR\fB\fIcase_sensitive\fR\fR\fB);\fR
.fi
.sp
.nf
\fBdnstable_res
dnstable_query_set_bailiwick(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    const char *\fR\fB\fIbailiwick\fR\fR\fB);\fR
.fi
.sp
.nf
\fBdnstable_res
dnstable_query_filter(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    struct dnstable_entry *\fR\fB\fIent\fR\fR\fB,
    bool *\fR\fB\fIfilter_res\fR\fR\fB);\fR
.fi
.sp
.nf
\fBstruct dnstable_iter *
dnstable_query_iter(struct dnstable_query *\fR\fB\fIq\fR\fR\fB,
    const struct mtbl_source *\fR\fB\fIsource\fR\fR\fB);\fR
.fi
.SH "DESCRIPTION"
.sp
\fBdnstable_query\fR objects encapsulate the search parameters used when querying a dnstable data source\&. They can be used to retrieve specific entries from a data source, or to test whether an already retrieved entry object matches the query\&.
.sp
A \fBdnstable_query\fR object is initialized by calling \fBdnstable_query_init\fR(), which takes the desired query type as a parameter\&. The \fBdnstable_query_set_\&...\fR() functions are then called to set the query parameters, as described below\&.
.sp
The functions with return type \fBdnstable_res\fR either return \fBdnstable_res_success\fR if the function completely successfully, or \fBdnstable_res_failure\fR otherwise\&. If \fBdnstable_res_failure\fR is returned, the \fBdnstable_query_get_error\fR() function can be called to obtain the error message text\&. (The string returned is valid for the \fBdnstable_query\fR object in question until the next error occurs or the query object is destroyed\&.)
.sp
\fBdnstable_query_filter\fR() tests whether the given \fBdnstable_entry\fR object would match the given \fBdnstable_query\fR object\&. The result is returned in the \fIfilter_res\fR parameter\&.
.sp
Once the query object has been constructed, \fBdnstable_query_iter\fR() iterates over all the matching entries in the specified mtbl source\&.
.SS "dnstable_query_set_\&...() functions"
.sp
\fBdnstable_query_set_rrtype\fR() sets the Resource Record type, which is specified as a string\&. The string parameter can be an RRtype mnemonic like \fI"A"\fR or \fI"NS"\fR or it can be the string "TYPE" followed by the decimal RRtype value\&.
.sp
\fBdnstable_query_set_bailiwick\fR() is only valid for \fIDNSTABLE_QUERY_TYPE_RRSET\fR type queries\&. If set, it causes the bailiwick field of RRset entries to be filtered against the value provided\&.
.sp
\fBdnstable_query_set_rrtype\fR() and \fBdnstable_query_set_bailiwick\fR() are optional\&. If not called, no RRtype or bailiwick filtering will be performed\&.
.sp
\fBdnstable_query_set_offset()\fR sets the number of initial rows to offset (e\&.g\&. skip) from the results\&. The default is 0, which means to not offset any rows\&.
.sp
\fBdnstable_query_set_aggregated\fR() sets if the results from queries should be aggregated\&. The default is \fItrue\fR for aggregated results\&.
.sp
\fBdnstable_query_set_data\fR() specifies the main search parameter and is required\&. Its meaning depends on the query type\&.
.sp
For \fIDNSTABLE_QUERY_TYPE_RRSET\fR queries, the search parameter is the RRset owner name\&. Left\- and right\- hand wildcards are permitted\&.
.sp
For \fIDNSTABLE_QUERY_TYPE_RDATA_NAME\fR queries, the search parameter is the domain name in the record data\&. Left\- and right\- hand wildcards are permitted\&.
.sp
For \fIDNSTABLE_QUERY_TYPE_RDATA_IP\fR queries, the search parameter is an IP address, IP prefix, or IP range\&. Both IPv4 and IPv6 are supported\&. If the search parameter contains a "/" character it will be treated as an IP prefix\&. If it contains a "\-" character it will be treated as an IP range\&. Otherwise, it will be treated as an address\&.
.sp
For \fIDNSTABLE_QUERY_TYPE_RDATA_RAW\fR queries, the search parameter is a hexadecimal string which will be directly compared against record data values\&.
.SH "SEE ALSO"
.sp
\fBdnstable\-encoding\fR(5), \fBdnstable_entry\fR(3), \fBdnstable_reader\fR(3), \fBmtbl_source\fR(3)
