'\" t
.\"     Title: dnstable_lookup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/08/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DNSTABLE_LOOKUP" "1" "05/08/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dnstable_lookup \- lookup individual records in a dnstable data file or set of data files
.SH "SYNOPSIS"
.sp
\fBdnstable_lookup\fR [\fB\-R\fR] [\fB\-j\fR] [\fB\-J\fR] [\fB\-u\fR] [\fB\-O #\fR] \fBrrset\fR <OWNER> [<RRTYPE> [<BAILIWICK>]]
.sp
\fBdnstable_lookup\fR [\fB\-R\fR] [\fB\-j\fR] [\fB\-J\fR] [\fB\-u\fR] [\fB\-O #\fR] \fBrdata ip\fR <ADDRESS | RANGE | PREFIX>
.sp
\fBdnstable_lookup\fR [\fB\-R\fR] [\fB\-j\fR] [\fB\-J\fR] [\fB\-u\fR] [\fB\-O #\fR] \fBrdata raw\fR <HEX STRING> [<RRTYPE>]
.sp
\fBdnstable_lookup\fR [\fB\-R\fR] [\fB\-j\fR] [\fB\-J\fR] [\fB\-u\fR] [\fB\-O #\fR] \fBrdata name\fR <RDATA NAME> [<RRTYPE>]
.SH "DESCRIPTION"
.sp
Looks up records in a dnstable data file\&. Results are printed to stdout in an ad\-hoc text format\&.
.sp
\fBdnstable_lookup rrset\fR returns RRsets matching the specified owner name (wildcards permitted)\&. A resource record type and bailiwick domain name can optionally be specified\&.
.sp
\fBdnstable_lookup rdata ip\fR returns A or AAAA type Resource Records matching the specified IP address, IP prefix, or IP range\&.
.sp
\fBdnstable_lookup rdata raw\fR returns Resource Records whose record data matches the specified data value, expressed as a hexademical string\&.
.sp
\fBdnstable_lookup rdata name\fR returns Resource Records whose record data matches the specified domain name\&.
.SH "OPTIONS"
.PP
\fB\-R\fR, \fB\-\-raw\fR
.RS 4
When using JSON format for output, add a hex representation of the raw rdata\&.
.RE
.PP
\fB\-j\fR
.RS 4
Use JSON format for output, with timestamps in epoch time (seconds since epoch)\&. Default is
\fIdig\fR
presentation format\&. One JSON\-formatted entry per line will be printed\&.
.RE
.PP
\fB\-J\fR
.RS 4
Use JSON format for output, with timestamps in human time (RFC3339 format)\&. Default is
\fIdig\fR
presentation format\&. One JSON\-formatted entry per line will be printed\&.
.RE
.PP
\fB\-u\fR
.RS 4
Output unaggregated results; default is aggregated results\&.
.RE
.PP
\fB\-O #\fR
.RS 4
Offset (e\&.g\&. skip) the first # results\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
Exactly one of the following environment variables must be set in order to specify the dnstable data file(s) to query\&.
.PP
\fBDNSTABLE_FNAME\fR
.RS 4
Path to a single dnstable data file\&.
.RE
.PP
\fBDNSTABLE_SETFILE\fR
.RS 4
Path to a "set file", a text file containing a newline separated list of dnstable data files on the filesystem\&. Results from all of the data files will be merged\&.
.RE
.SH "EXAMPLES"
.sp
$ export DNSTABLE_FNAME=/path/to/dns\&.mtbl
.sp
$ dnstable_lookup rrset www\&.example\&.com
.sp
$ dnstable_lookup rrset example\&.com ns com
.sp
$ dnstable_lookup rdata ip 192\&.0\&.2\&.1
.sp
$ dnstable_lookup rdata ip 198\&.51\&.100\&.0/24
.sp
$ dnstable_lookup rdata ip 203\&.0\&.113\&.1\-203\&.0\&.113\&.100
.sp
$ dnstable_lookup \-j rdata ip 2001:db8::/32
.sp
$ dnstable_lookup \-R \-j rdata ip 2001:db8::/32
.sp
$ dnstable_lookup \-u rdata ip 2001:db8::/32
.sp
$ dnstable_lookup \-O 10 rdata ip 2001:db8::/32
.sp
$ dnstable_lookup rdata raw c00505f1
.sp
$ dnstable_lookup rdata name BLACKHOLE\-1\&.IANA\&.ORG
